options:
    q51-prefix: &8[&bQ51&8]&r

command /q51vil [<text>]:
    description: Stores quick notes for villager hall plans. (variant #51)
    trigger:
        set {_p} to "{@q51-prefix}"
        set {villagernote::%player's uuid%} to "Librarian -> Toolsmith -> Armorer"
        send "%{_p}% &aSaved default villager route plan."

on join:
    send "{@q51-prefix} &7Use /q51vil for module #51." to player
